---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown
baseurl: azurecosmosdb

### content configuration ###
title:       "Azure Cosmos DB"
keywords:    "Azure Cosmos DB"
description: "Everything you need to learn Azure Cosmos DB"


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#ffffff'
  blue:      '#0f0f0f'
  green:     '#9bcf2f'
  red:       '#ff0000'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

    
kramdown:
  auto_ids:  false

